In [5]:
import numpy as np
threshold=.8

In [6]:
X = np.random.random((3000, 2000))

In [7]:
n = X.shape[0]
index = np.random.permutation(np.arange(n))
train_index = index[:int(n * threshold)]
test_index = index[int(n * threshold):]

In [8]:
index

array([2767, 1796, 2535, ..., 2792, 2000, 2401])

In [9]:
train_index

array([2767, 1796, 2535, ..., 1936,  554, 2155])

In [10]:
test_index

array([1959, 2032, 1895, 2429, 2911,  703,  861,  699, 2878, 2472, 1595,
        508,  851,  814,  744, 1428, 2296,  254, 1563,   31,   38,  719,
        103, 2744, 2098, 2144, 1328,  999, 1521, 1322, 2702,  408, 2575,
        937,  992, 1456, 1578, 2235, 1547, 1839, 2448, 1312,  911, 1757,
        399, 2906, 2865, 2341, 1649, 2684,  808, 2332, 2983,  122,   19,
       2600, 2005,  436, 2672,  125, 1359, 2019,  123, 1769, 2414,  365,
       2254, 2509, 2116, 1735, 2770,  337, 1212,   42, 1787, 2736, 1956,
        479,  923,  389, 2843, 2704, 2691, 1860, 2999,   76,  153, 2747,
       1527,  213, 2162, 1445, 2637,  680,  166,  209,  709, 1873, 2741,
        179, 1665,  684, 1584,  154, 2778, 2488, 2119,  141, 1699, 2376,
       2829, 2055,  848, 2108, 2905, 1612, 2614,  542, 2257, 1382,  705,
       2106, 2640, 2449, 1167, 1908, 1827, 1740,  132, 1078,  729, 2647,
        734, 2973, 2615, 2456, 1395,  835, 1014, 1261,  111, 1609, 2033,
        828,  546, 1734, 2810, 2192, 2089, 1551, 21

In [11]:
X[train_index]

array([[0.06925838, 0.82827531, 0.01919232, ..., 0.18735875, 0.86483259,
        0.31246191],
       [0.30902415, 0.10586868, 0.60326066, ..., 0.45214082, 0.31064789,
        0.7600693 ],
       [0.12012146, 0.03811123, 0.15370919, ..., 0.00682021, 0.74855156,
        0.1061331 ],
       ...,
       [0.81556867, 0.92701838, 0.60311039, ..., 0.72336837, 0.10053059,
        0.13989468],
       [0.64813235, 0.37517382, 0.83164956, ..., 0.89574869, 0.69020296,
        0.98117882],
       [0.99500877, 0.04020668, 0.25610722, ..., 0.21053949, 0.61104384,
        0.16395074]])